### PR TITLE
nightly/enc.sh: Build enc in repository root _output/enc

### PR DESCRIPTION
**Pull request by techtonik**
nighly build files for Encyclopedia will be available at:

    _output/outfinalnew32/Encyclopedia
    _output/outfinalnew64/Encyclopedia

And the build itself is taking place in:

    _output/enc  - which is a 1:1 copy from the repo

### CODE REVIEW

**Comment by techtonik** [comment]
If this layout is okay I will update the rest of `nightly` scripts to follow the same scheme.

**Comment by trexinc** [comment]
What is the purpose of those changes?

**Comment by trexinc** [comment]
And in any case this breaks Far build.

**Comment by techtonik** [comment]
1. This is needed to understand where files produced by nightly build go. It also makes it possible to run build scripts from any place.
2. Where are logs from nightly builds? It could be tested by Travis.

**Comment by techtonik** [comment]
So this is a way to document this certain dir structure in code. I need to get .hlf files from source on Linux and upload them to https://fardocs.netlify.com/ for experiments. Started with `enc.sh`, because I know its layout.

**Comment by techtonik** [comment]
@trexinc what is the dir structure that scripts expect? Is it possible to figure out what changes are made on disk without going through the source code?

**Pull request closed without merging**
