### PR TITLE
Described `End` key behavior on the Help @MiscCmd page, section "Dialogs".

### PR DESCRIPTION
**Pull request by MKadaner**
## Summary
Including Russian translation, credit goes to my support team.

 
## References
As per [discussion](https://github.com/FarGroup/FarManager/pull/662#issuecomment-1492976441).

## Checklist
- [X] I have followed the [contributing guidelines](https://github.com/FarGroup/FarManager/blob/master/CONTRIBUTING.md).
- [X] I have discussed this with project maintainers: #662 <br/>
If not checked, I accept that this work might be rejected in favor of a different great big ineffable plan.<br/>

### CODE REVIEW

**Comment by bitraid** [comment]
It seems that `Home` (focus first element) is also missing.

**Comment by HamRusTal** [comment]
> It seems that `Home` (focus first element) is also missing.

Interesting! And it doesn't work for me in Editor's Find/Replace dialogs in all recent Far versions.
@MKadaner This looks like a regression resulting from Search/Replace dialogs unification.

**Comment by HamRusTal** [comment]
Написано:
```
 Вы также можете использовать #End#, чтобы поместить курсор в диалогах
на элемент по умолчанию, если фокус не находится на элементе, который
сам обрабатывает #End#, как, например, строка редактирования.
```
Но «курсор в диалоге» — это какое-то странное обозначение, когда речь идёт не о полях ввода текста. Предлагаю заменить «поместить курсор в диалогах» на «установить фокус в диалоговом окне».

**Comment by MKadaner** [comment]
> It seems that Home (focus first element) is also missing.

No good deed goes unpunished. I'll add a note.

> Interesting! And it doesn't work for me in Editor's Find/Replace dialogs in all recent Far versions.

It's because the first element is `Text` radio button, which is hidden in the Editor. Could you please create a bug here? Fixing it is certainly beyond the scope of this PR.

> ... «курсор в диалоге» ...

Copy-paste from the line above. Apparently, I have not even read this nonsense. 😄 Will fix.

**Comment by MKadaner** [comment]
Addressed comment, rebased, ready to merge (no changelog).

**Comment by alabuzhev** [comment]
Thanks

**Comment by MKadaner** [comment]
Thank you.

**Pull request merged**
