### PR TITLE
Combined Russian and English changelogs into a single file.

### PR DESCRIPTION
**Pull request by MKadaner**
See #253 for the underlying discussion.

### CODE REVIEW

**Comment by alabuzhev** [comment]
[publish.sh](https://github.com/FarGroup/FarManager/blob/13d47a573f87c8a2a3d5bf4d1e9ae07e98ed80b2/misc/nightly/publish.sh#L35) - this takes the first line of the changelog and uses it elsewhere (e.g. [update3.php](https://farmanager.com/nightly/update3.php)). It is expected that that line consists of a timestamp and a build. After merging this PR the fist line will always be `---------------`. We need to either update that script to take the 2nd line instead or don't put a separator on the top.

[download.en.php](https://github.com/FarGroup/www/blob/57b01fe21e1e3e537a6225f4bc8fec6ad66ca9e5/site/inc/download.en.php#L11) should be updated as well.

**Comment by MKadaner** [comment]
Thank you for pointing out missing changes. I slightly prefer keeping the separator at the top of the combined changelog, so I updated `publish.sh`. I created supporting [PR in FarGroup/www](https://github.com/FarGroup/www/pull/6). Please merge them together when everything is ready.

For now, I merged the latest master into my PR branch and created separate commit. This way you can review incremental changes. When the change is ready for merge, I will rebase my branch and squash commits.

**Review by alabuzhev — APPROVED** [review]

**Comment by MKadaner** [comment]
Thank you. I eventually managed to mechanically squash-rebase my originally-merged branch to master, so this new commit should be correct. Also, before force-pushing, I checked that all files in the new commit, including `changelog`, were byte for byte the same as on the branch.

**Comment by MKadaner** [comment]
Thank you.

**Pull request merged**
