### PR TITLE
Added plugins to HlfChecker

### PR DESCRIPTION
**Pull request by MKadaner**
Also:
- Made related and unrelated improvements in the checker.
- Added HlfChecker.cmd to run the checker from the command line. See the comment inside.
- The checker now automatically corrects blank lines and removes trailing spaces. Use `git diff` to verify the result.
- Cleansed some plugin help files. As of this commit, Ftp plugin help has the following issues:
```

--------------------------------------------------------------------------------
Validating diretory ftp...

Parsing FtpEng.hlf...
FtpEng.hlf(1664): Warning: Empty Topic @FTPQueueAddItem
FtpEng.hlf(1666): Warning: Empty Topic @FTPExtHost

*** Warnings in FtpEng.hlf

Writing back FtpEng.hlf...

Parsing FtpBel.hlf...
FtpBel.hlf(1698): Warning: Empty Topic @FTPQueueAddItem
FtpBel.hlf(1700): Warning: Empty Topic @FTPExtHost

*** Warnings in FtpBel.hlf

Writing back FtpBel.hlf...

Comparing FtpEng.hlf and FtpBel.hlf...

Parsing FtpCze.hlf...

Writing back FtpCze.hlf...

Comparing FtpEng.hlf and FtpCze.hlf...

Mismatch:
    FtpEng.hlf: Prologue.Count: 3
    FtpCze.hlf: Prologue.Count: 2

Mismatch:
    FtpEng.hlf: Topics.Count: 24
    FtpCze.hlf: Topics.Count: 7

*** Issues in FtpCze.hlf

Parsing FtpGer.hlf...

Writing back FtpGer.hlf...

Comparing FtpEng.hlf and FtpGer.hlf...

Mismatch:
    FtpEng.hlf: Prologue.Count: 3
    FtpGer.hlf: Prologue.Count: 2

Mismatch:
    FtpEng.hlf: Topics.Count: 24
    FtpGer.hlf: Topics.Count: 6

*** Issues in FtpGer.hlf

Parsing FtpHun.hlf...

Writing back FtpHun.hlf...

Comparing FtpEng.hlf and FtpHun.hlf...

Mismatch:
    FtpEng.hlf: Prologue.Count: 3
    FtpHun.hlf: Prologue.Count: 2

Mismatch:
    FtpEng.hlf: Topics.Count: 24
    FtpHun.hlf: Topics.Count: 6

*** Issues in FtpHun.hlf

Parsing FtpPol.hlf...
FtpPol.hlf(1664): Warning: Empty Topic @FTPQueueAddItem
FtpPol.hlf(1666): Warning: Empty Topic @FTPExtHost

*** Warnings in FtpPol.hlf

Writing back FtpPol.hlf...

Comparing FtpEng.hlf and FtpPol.hlf...

Parsing FtpRus.hlf...
FtpRus.hlf(1726): Warning: Empty Topic @FTPQueueAddItem
FtpRus.hlf(1728): Warning: Empty Topic @FTPExtHost

*** Warnings in FtpRus.hlf

Writing back FtpRus.hlf...

Comparing FtpEng.hlf and FtpRus.hlf...

Mismatch: Topics[5]:
    FtpEng.hlf: Topics["@CopyDialogVALS"].Paragraphs.Count: 35
    FtpRus.hlf: Topics["@CopyDialogVALS"].Paragraphs.Count: 31

Mismatch: Topics[11]:
    FtpEng.hlf: Topics["@FTPConnect"].Paragraphs.Count: 21
    FtpRus.hlf: Topics["@FTPConnect"].Paragraphs.Count: 20

Mismatch: Topics[12]:
    FtpEng.hlf: Topics["@Config"].Paragraphs.Count: 40
    FtpRus.hlf: Topics["@Config"].Paragraphs.Count: 39

*** Issues in FtpRus.hlf

Parsing FtpUkr.hlf...

Writing back FtpUkr.hlf...

Comparing FtpEng.hlf and FtpUkr.hlf...

Mismatch:
    FtpEng.hlf: Prologue.Count: 3
    FtpUkr.hlf: Prologue.Count: 2

Mismatch:
    FtpEng.hlf: Topics.Count: 24
    FtpUkr.hlf: Topics.Count: 6

*** Issues in FtpUkr.hlf
```

### CODE REVIEW

**Comment by MKadaner** [comment]
Thank you.

**Comment by alabuzhev** [comment]
Thank you.
No need to worry about Ftp*.hlf - the plugin is no longer a part of the distribution package and hasn't been supported or developed for years. Translations other than en/ru are for older versions and therefore incomplete, I added them just because it's better than nothing. Maybe it would even be better to skip it entirely in the script to reduce the noise.

**Comment by MKadaner** [comment]
Where is the source of truth about active plugins? Is it `misc\msi-installer\files.wxs` or something else? I can limit default plugin directory enumeration to those listed in such place. It still will be possible to specify the directory manually.

**Comment by alabuzhev** [comment]
Any of the following should be relevant:
- misc\msi-installer\files.wxs
- misc\nightly\plugins.sh
- plugins\makefile_all_vc

However, I probably wouldn't limit the scope of the tool to "active" only - we still support some inactive ones, e.g. multiarc, and there's no harm in having help files synchronised nicely there.

Only FTP is "special" due to the massive changes happened there in the 1.70 era.

**Comment by MKadaner** [comment]
Got it! Will do. Thanks

**Pull request merged**
