### PR TITLE
Network refactor

### PR DESCRIPTION
**Pull request by ctapmex**
## Summary
First steps restoring work network plugin on win10. For begin only some refactoring.
Next changes (in next PR, or in current) - restore favorites , and support smb

 
## Checklist
- [x] I have followed the [contributing guidelines](https://github.com/FarGroup/FarManager/blob/master/CONTRIBUTING.md).
- [x] I have discussed this with project maintainers:  <br/>
If not checked, I accept that this work might be rejected in favor of a different grand plan.<br/>

### CODE REVIEW

**Review by alabuzhev — APPROVED** [review]
Looks good, please rebase and squash 'refactoring' comments.
It's probably better to keep 'reformatting code to the standard' as a separate commit though.

**Comment by ctapmex** [comment]
changed

**Comment by alabuzhev** [comment]
Rebase again please.

**Comment by ctapmex** [comment]
again changed

**Comment by alabuzhev** [comment]
Thanks

**Pull request merged**
