### PR TITLE
Fix broken links in Encyclopedia

### PR DESCRIPTION
**Pull request by johnd0e**

### CODE REVIEW

**Comment by johnd0e** [comment]
Остался один неясный момент: есть целый ряд линков указывающих на несуществующий путь [win32/..](https://github.com/search?q=repo%3AFarGroup%2FFarManager%20%22win32%2F&type=code). Для публикации на сайте по ним проходится [скрипт](https://github.com/FarGroup/FarManager/blob/17654ef939555f2e6ec586e1e6f1239548e2e931/enc/tools/tool.make_inet.py#L59), и заменяет их на тот же `../msdn.html?TERM`, см. например https://fargroup.github.io/api/ru/fsf/mktemp.html
Проблема в том, что для chm ничего такого не делается, и ссылки остаются мёртвыми. [Очевидно](https://fargroup.github.io/api/ru/articles/forauthors.html) раньше был какой-то скрипт, формировавший специальные линки для локальной копии MSDN.

Раз уж дошли до этого руки, полагаю надо сделать всё однотипно, например `win32/..` заменить на `msdn.html?..`
С другой стороны, зачем тут вообще нужен посредник типа msdn.html, можно же просто сделать прямые линки везде.

Как вариант, в коде везде оставить `win32/..`, а полный линк формировать динамически (javascript).

**Comment by johnd0e** [comment]
> [...]а полный линк формировать динамически (javascript).

Так и сделал.

Ссылка на WinAPI функцию (не описанную в Энциклопедии), для Вашей статьи, например для функции GetLastError:
```html
<a class="msdocs">GetLastError</a>
```

При помощи javascript такая ссылка автоматически преобразуется в полную ссылку для поиска на сайте Microsoft: [GetLastError](https://learn.microsoft.com/search/?terms=GetLastError).

Код: https://github.com/FarGroup/FarManager/blob/34dbf70984456a49ec3f7530d011bc898400cf55/enc/enc_rus/meta/links.js

**Comment by johnd0e** [comment]
@alabuzhev ?

**Comment by johnd0e** [comment]
@alabuzhev ?

**Comment by alabuzhev** [comment]
863ddc4dd8a526e686096ad3c4334ea5dce759a6 `No need to encode *.html to cp1251 for chm` - how come?

**Comment by alabuzhev** [comment]
Please don't get me wrong, I appreciate the effort, but, as discussed elsewhere, a PR should ideally focus on a single, logically atomic change. This way it's much easier to review and understand it.

When a PR is called "Fix broken links in Encyclopedia", a maintainer usually expects exactly that: _"fixing broken links in HTML, either because some sites moved to new addresses or because they're gone for good and we're using web archive or something. Content only. Low risk. It probably won't break the build or introduce bugs. I can press "Merge" and move on."_

But if there's also some refactoring and some shenanigans with encoding and removing some dead code and articles and something else, a maintainer will likely think _"Nah, I'm not doing it. Maybe other time or maybe someone else will review it"_ and it will sit there for months and you will feel neglected. And, obviously, _any_ issues with _any_ of those extra changes will block _the whole thing_ from merging.

There are 5 logically independent commits here and only one of them is directly related to the PR's subject (or so it seems).
Could you please move other commits to separate PRs?

**Comment by johnd0e** [comment]
> `https://github.com/FarGroup/FarManager/commit/863ddc4dd8a526e686096ad3c4334ea5dce759a6 No need to encode *.html to cp1251 for chm` - how come?

I have build *.chm and it works ok for me with utf-8.

> PR should ideally focus on a single, logically atomic change.

- I have started from replacing dead links, looking for replacements for them
  - Removing dead article was done by the way, after I found that it is not referenced by any link.
    I see it as very minor change to have separate PR for that. Still, it is connected to links.
- Then I found that msdn links are dead as well, and this PR subject is "Fix broken links", so...
- The last two commits are not related to subject, they are just logical finish of previous changes.
   As they are based on previous changes, they are not really "atomic" and "independent", they should be applied on top of all.
   But sure I can make it in separate PR.

**Comment by alabuzhev** [comment]
> I have build *.chm and it works ok for me with utf-8.

The index too?

> I have started from replacing dead links...

Exactly, it's a neverending story, but the sooner we take a break and fix the state the better.

**Comment by johnd0e** [comment]
> The index too?

All *.html are ok.

These 2 files only should be kept in ANSI:
pluginsr.hhc
pluginsr.hhk

**Review by alabuzhev — APPROVED** [review]

**Comment by alabuzhev** [comment]
> Only these 2 files should be in 1251

That's great news, let's do it then.

**Comment by johnd0e** [comment]
> PR should ideally focus on a single, logically atomic change. This way it's much easier to review and understand it.

Speaking about that: https://stacking.dev/

**Comment by alabuzhev** [comment]
That's neat, as long as we don't have dozens of commits between main 1 and main 3 and dozens of simultaneously developed features, otherwise this:
image
can quickly become this:
image

**Pull request merged**
