### PR TITLE
add Belarussian language

### PR DESCRIPTION
**Pull request by lidacity**
дадана беларуская мова
Добавлен Белорусский язык

### CODE REVIEW

**Comment by lidacity** [comment]
хм, что за ошибки? локально вроде собирается...

**Comment by alabuzhev** [comment]
No problem, I've fixed them.

Thanks, merged.

**Comment by alabuzhev** [comment]
@lidacity, would you like to be mentioned in [CONTRIBUTORS.md](https://github.com/FarGroup/FarManager/blob/master/CONTRIBUTORS.md)?
If so, how?

**Comment by lidacity** [comment]
> @lidacity, would you like to be mentioned in [CONTRIBUTORS.md](https://github.com/FarGroup/FarManager/blob/master/CONTRIBUTORS.md)?
> If so, how?
Dzmitry Kosko

**Pull request merged**
