### PR TITLE
Reorder python file

### PR DESCRIPTION
**Pull request by snxx-lppxx**
Changed a little.

### CODE REVIEW

**Comment by alabuzhev** [comment]
@snxx-lppxx could you please explain what your PR does, why it's needed etc.?

**Comment by snxx-lppxx** [comment]
@alabuzhev, changed the code style. The code will work the same, but looks better.

**Comment by techtonik** [comment]
@snxx-lppxx usually people don't add such commit, because they add extra steps while navigating source history for potential problems. But adding https://github.com/psf/black to CI may by a good choice to avoid wasting time on code formatting matters.

**Comment by alabuzhev** [comment]
@snxx-lppxx, what @techtonik said.

Adhering to a single style is a good thing in general, but replacing `"` with `'` in some supplementary script doesn't look that useful, it will only add noise.

Technically, PEP 8 [explicitly abstains from enforcing this](https://www.python.org/dev/peps/pep-0008/#string-quotes), so it's a matter of taste. Since our primary language is C++ here, double quotes just look more natural around strings.

**Pull request closed without merging**
