### PR TITLE
Remove outdated changelogs

### PR DESCRIPTION
**Pull request by techtonik**
There is repository history now.

### CODE REVIEW

**Comment by alabuzhev** [comment]
I believe we [discussed this already](https://github.com/FarGroup/FarManager/pull/49) some time ago.

**Comment by techtonik** [comment]
The nail that still sticks in my head. Whatever..

**Comment by johnd0e** [comment]
Well, those changelogs are actually outdated.
What'd be useful - track api changes in some document (and we have one, outdated too).

**Comment by alabuzhev** [comment]
Even outdated, these logs still can be useful. I see no harm in having them there.
Updates are always welcome.

**Pull request closed without merging**
