### PR TITLE
Converted changelog dates to ISO 8601 format.

### PR DESCRIPTION
**Pull request by MKadaner**
## Summary
Converted date-time in changelog headers to [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.

## Checklist
- [X] I have followed the [contributing guidelines](https://github.com/FarGroup/FarManager/blob/master/CONTRIBUTING.md).
- [X] I have discussed this with project maintainers: #626 <br/>
If not checked, I accept that this work might be rejected in favor of a different great big ineffable plan.<br/>

## Details
Please review
<details><summary>The script used for conversion</summary>
<p>

```C#
const string FarManagerRoot = @"D:\DEV\FarManager";
readonly IEnumerable<string> AllChangelogs = Directory
    .EnumerateFiles(FarManagerRoot, "changelog", SearchOption.AllDirectories)
    .Where(chl => Path.GetFileName(chl) == "changelog");

void Main()
{
    foreach (var changelog in AllChangelogs)
    {
        changelog.Dump();
        var lines = File.ReadAllLines(changelog).ToList();

        if (ValidateHeaders(lines).Any())
        {
            ValidateHeaders(lines).Dump();
            return;
        }

        File.WriteAllLines(changelog, TransformHeaders(lines));
    }
}

readonly Regex DateLike = new Regex(@"^\D[^[=]+\d{2}\D\d{2}\D\d{4}", RegexOptions.Compiled);
readonly Regex FullHeader =
    new Regex(@"^([&+\s\w\d-]+) (\d{2})\.(\d{2})\.(\d{4}) (\d{2}:\d{2}:\d{2}) ([+-]\d{2})(\d{2})(.*)$", RegexOptions.Compiled);
//               1              2        3        4       5                   6          7      8

IEnumerable<string> ValidateHeaders(IEnumerable<string> lines)
{
    foreach (var line in lines)
    {
        if (DateLike.IsMatch(line) && !FullHeader.IsMatch(line)) yield return line;
    }
}

IEnumerable<string> TransformHeaders(IEnumerable<string> lines)
{
    foreach (var line in lines)
    {
        yield return FullHeader.Replace(line, "$1 $4-$3-$2 $5$6:$7$8");
    }
}
```

</p>
</details>

### CODE REVIEW

**Comment by alabuzhev** [comment]
Thanks

**Comment by SleepingCatSC** [comment]
@alabuzhev Just consider that FAR GitHub repo already has countless amount of archives with old date and time format. Anyway thanks for that change :)

**Comment by MKadaner** [comment]
Thank you for merging with my previous commit. I thought that since these two PRs affect different files, they could be merged independently in in any order. Isn't it so?

**Comment by alabuzhev** [comment]
@SleepingCatSC we are obviously not going to repack any old artefacts.

@MKadaner they could indeed, I simply prefer this:
image
to this:
image
when possible.

**Comment by MKadaner** [comment]
Noted. Will avoid stacking PRs in the future.

**Comment by alabuzhev** [comment]
No worries.

**Comment by SleepingCatSC** [comment]
I've noticed that skipik doesn't seem to abide new date and time format. Over time it'll cause a partial inconsistency.
```
Far30b6108.x64.20230224\changelog

╔═════════════════ Occurrences: 5, lines: 5 ══════════════════╗
║  7:1         │skipik 23.02.2023 13:50:41 +0300 - build 6107 ║ <---
║  928:1       │skipik 2022-02-23 19:46:25+03:00 - build 5962 ║
║  983:1       │skipik 2022-01-07 14:11:12+03:00 - build 5953 ║
║  993:1       │skipik 2022-01-03 22:53:17+03:00 - build 5951 ║
║  1130:1      │skipik 2021-12-01 21:42:37+03:00 - build 5925 ║
╚══════════ Ctrl+Enter F5 Gray + Ctrl+Up Ctrl+Down ═══════════╝
```

Just tell all the contributors to update their ChangelogHeader.lua and ChangelogCheckEnglish.lua macros to avoid such cases in future.

**Comment by HamRusTal** [comment]
Probably the Changelog example in [`CONTRIBUTING.md`](https://github.com/FarGroup/FarManager/blob/master/CONTRIBUTING.md) has to be updated too.

**Pull request merged**
