### PR TITLE
Viewer now uses the standard Search dialog.

### PR DESCRIPTION
**Pull request by MKadaner**
## Summary
This is it: Viewer now uses the standard Search dialog. No changes in behavior are expected except for the two removed features (see _Details_).

 
## References
- #584
- #614

## Checklist
- [X] I have followed the [contributing guidelines](https://github.com/FarGroup/FarManager/blob/master/CONTRIBUTING.md).
- [X] I have discussed this with project maintainers: See _References_ above.<br/>
If not checked, I accept that this work might be rejected in favor of another great big ineffable plan.<br/>

## Details
Also removed:
- Opening Viewer Search dialog on typing the first character of the search pattern.
- _Search dialog auto-focus_ feature. We discussed it somewhere, but I could not find the place.

What else did I forget to remove?

### CODE REVIEW

**Comment by MKadaner** [comment]
@rohitab, It would be great if you could test this change. The most interesting things to test are search for Hex in Viewer and saving / restoring dialog settings across searches and Viewer / Editor instances. In both cases no regressions are expected, but I did not attempt to address any known bugs / issues in these areas.

**Comment by rohitab** [comment]
Sure, I will test it out. Might not be able to get to it until tomorrow though, but I'll definitely try.

**Comment by MKadaner** [comment]
Thank you! No rush at all.

**Review by alabuzhev — APPROVED** [review]

**Comment by MKadaner** [comment]
Thank you.

Changelog / version / rebased / squashed / ready.

**Comment by rohitab** [comment]
@MKadaner I just tested your changes and everything appears to be working fine. I did not find any issues with the search.

Since you removed `Viewer.SearchEditFocus`, do you think it should be removed from the macro testing code as well?

https://github.com/FarGroup/FarManager/blob/833c93989cc63b3fde1a9f85552bd4d730db2b7b/plugins/luamacro/macrotest.lua#L1006-L1008

Right now, it won't make a difference since the code to test the configuration is commented out.

https://github.com/FarGroup/FarManager/blob/833c93989cc63b3fde1a9f85552bd4d730db2b7b/plugins/luamacro/macrotest.lua#L1061

It's most likely commented since there are a lot of other left over settings that were never removed, and some settings where the type changed. Examples include `Dialog.EditHistory`, `Interface.ShiftsKeyRules` and `Interface.ClearType`. The `test_Far_GetConfig` function fails even in previous versions due to this.

**Comment by MKadaner** [comment]
Thank you for testing, @rohitab, and for discovering `macrotest.lua`. Frankly, I do not know what I should do with it. For now, I commented `Viewer.SearchEditFocus` out of the test. Tagging @alabuzhev to weigh in.

**Comment by alabuzhev** [comment]
macrotest.lua runs [during CI](https://github.com/FarGroup/FarManager/blob/833c93989cc63b3fde1a9f85552bd4d730db2b7b/appveyor.yml#L140-L141).
If some parameters no longer exist please remove them from the test.

**Comment by MKadaner** [comment]
As Rohitab noted, Far config test was commented out [six years ago](https://github.com/FarGroup/FarManager/commit/6b808a110570692552a1a722ae07f5a94124a518#diff-710a0914f11ef9f5fae580bf597428cb48813899210bf0b99fec1e60424692a5) (even though macrotest.lua is still executed):

https://github.com/FarGroup/FarManager/blob/833c93989cc63b3fde1a9f85552bd4d730db2b7b/plugins/luamacro/macrotest.lua#L1061

I am not sure what is the value of this test, but let me fix it in a separate PR. It has nothing to do with Viewer Search. I created [a bug](https://github.com/FarGroup/FarManager/issues/624) to track this issue. You can assign it to me.

**Comment by MKadaner** [comment]
Thank you!

**Pull request merged**
